version: "3.9"

services:
  #KlicService
  klicservice:
    image: klicservice:${KLICSERVICE_IMAGE_TAG}
    restart: always
    container_name: klicservice
    build:
      context: ./klicservice
      dockerfile: KlicService/Dockerfile
    networks:
      - marxact-dev-network
    environment:
      - ASPNETCORE_URLS=${KLICSERVICE_ASPNETCORE_URLS}
      - ASPNETCORE_ENVIRONMENT=${KLICSERVICE_ASPNETCORE_ENVIRONMENT}
      - SURVEYSERVICE_DB_HOST=${KLICSERVICE_DB_HOST}
      - SURVEYSERVICE_DB_NAME=${KLICSERVICE_DB}
      - SURVEYSERVICE_DB_USER=${KLICSERVICE_USER}
      - SURVEYSERVICE_DB_PASSWORD=${KLICSERVICE_PASSWORD}
      - SURVEYSERVICE_DB_PORT=${KLICSERVICE_DB_PORT}
      - SURVEYSERVICE_SSL_MODE=${KLICSERVICE_SSL_MODE}
      - ASPNETCORE_Kestrel__Certificates__Default__Path=${KLICSERVICE_CERT_PATH}
      - ASPNETCORE_Kestrel__Certificates__Default__Password=${KLICSERVICE_CERT_PASSWORD}
    ports:
      - "${KLICSERVICE_PORT}:${KLICSERVICE_PORT}"
    extra_hosts:
      - "change.me:host-gateway"

networks:
  marxact-dev-network:
