version: "3.9"

services:
  #downloadservice
  downloadservice:
    image: downloadservice:${DOWNLOADSERVICE_IMAGE_TAG}
    restart: always
    container_name: downloadservice
    build:
      context: ./DownloadService
      dockerfile: DownloadService/Dockerfile
    networks:
      - marxact-dev-network
    environment:
      - ASPNETCORE_URLS=${DOWNLOADSERVICE_ASPNETCORE_URLS}
      - ASPNETCORE_ENVIRONMENT=${DOWNLOADSERVICE_ASPNETCORE_ENVIRONMENT}
      - SURVEYSERVICE_SSL_MODE=${DOWNLOADSERVICE_SSL_MODE}
      - ASPNETCORE_Kestrel__Certificates__Default__Path=${DOWNLOADSERVICE_CERT_PATH}
      - ASPNETCORE_Kestrel__Certificates__Default__Password=${DOWNLOADSERVICE_CERT_PASSWORD}
    ports:
      - "${DOWNLOADSERVICE_PORT}:${DOWNLOADSERVICE_PORT}"
    extra_hosts:
      - "change.me:host-gateway"

networks:
  marxact-dev-network:
