<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="RdNapTrans2008\**" />
    <Content Remove="RdNapTrans2008\**" />
    <EmbeddedResource Remove="RdNapTrans2008\**" />
    <None Remove="RdNapTrans2008\**" />
  </ItemGroup>


  <ItemGroup>
    <PackageReference Include="MassTransit" Version="7.3.1" />
    <PackageReference Include="MassTransit.RabbitMQ" Version="7.3.1" />
    <PackageReference Include="MassTransit.AspNetCore" Version="7.3.1" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.NewtonsoftJson" Version="8.0.13" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.13" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="9.0.1" />
    <PackageReference Include="Microsoft.Extensions.Diagnostics.HealthChecks" Version="8.0.13" />
    <PackageReference Include="GeoJSON" Version="2.3.1" />
    <PackageReference Include="IdentityServer4.AccessTokenValidation" Version="3.0.1" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="8.0.11" />
  </ItemGroup>


  <ItemGroup>
    <ProjectReference Include="..\auth-contracts\AuthContractsClassLib\AuthContracts.csproj" />
    <ProjectReference Include="..\uni-auth-helper\UniAuthHelper.csproj" />
  </ItemGroup>
  <Import Project="..\unisharedmodels\UNISharedModels\UNISharedModels.projitems" Label="Shared" />
  <Import Project="..\surveycontracts\SurveyContracts\SurveyContracts.projitems" Label="Shared" />
</Project>
